# General Jekyll Config
highlighter: rouge
url: https://conanhxb.github.io
lsi: false
permalink: /blog/:year/:month/:day/:title/
category_dir: blog/categories
paginate: 100
paginate_path: "page:num"
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
